# Generated by Django 5.1.5 on 2025-01-24 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0003_remove_profile_first_name_alter_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
    ]
